Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Use Horner's algorithm to compute and return the polynomial
#    p(x) = a[0] + a[1] x^1 + a[2] x^2 + ... + a[n-1] x^(n-1)
# evaluated at x.
def horners(a, x):
    result = poly[len(a)-1]
    for i in range(len(a)-2, -1, -1):
        result = result*x + a[i]
    return result
 
# Let us the horners function defined above to evaluate the polynomial from the example above
coefficients = [-0.147, 3., -6., 1.]
x = 4.71

print("p(x) = ", horners(coefficients, x))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[1;32m     11[0m coefficients [38;5;241m=[39m [[38;5;241m-[39m[38;5;241m0.147[39m, [38;5;241m3.[39m, [38;5;241m-[39m[38;5;241m6.[39m, [38;5;241m1.[39m]
[1;32m     12[0m x [38;5;241m=[39m [38;5;241m4.71[39m
[0;32m---> 14[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mp(x) = [39m[38;5;124m"[39m, [43mhorners[49m[43m([49m[43mcoefficients[49m[43m,[49m[43m [49m[43mx[49m[43m)[49m)

Input [0;32mIn [1][0m, in [0;36mhorners[0;34m(a, x)[0m
[1;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mhorners[39m(a, x):
[0;32m----> 5[0m     result [38;5;241m=[39m [43mpoly[49m[[38;5;28mlen[39m(a)[38;5;241m-[39m[38;5;241m1[39m]
[1;32m      6[0m     [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m(a)[38;5;241m-[39m[38;5;241m2[39m, [38;5;241m-[39m[38;5;241m1[39m, [38;5;241m-[39m[38;5;241m1[39m):
[1;32m      7[0m         result [38;5;241m=[39m result[38;5;241m*[39mx [38;5;241m+[39m a[i]

[0;31mNameError[0m: name 'poly' is not defined
NameError: name 'poly' is not defined

